name: nyc_311_analytics
version: "1.0.0"
config-version: 2

profile: nyc_311_analytics

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_311_analytics:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
