CREATE DATABASE analytics OWNER airflow;

\connect analytics

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION airflow;
CREATE SCHEMA IF NOT EXISTS staging AUTHORIZATION airflow;
CREATE SCHEMA IF NOT EXISTS marts AUTHORIZATION airflow;

GRANT ALL PRIVILEGES ON DATABASE analytics TO airflow;
GRANT ALL ON SCHEMA raw TO airflow;
GRANT ALL ON SCHEMA staging TO airflow;
GRANT ALL ON SCHEMA marts TO airflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT ALL ON TABLES TO airflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT ALL ON TABLES TO airflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA marts GRANT ALL ON TABLES TO airflow;
